### ISSUE TITLE
Change PipelineStep Enum names

### ISSUE THREAD

**Issue by SanojPunchihewa** [AnjanaSenanayake/f5n_server#15]
`SAMTOOL_INDEX` and `SAMTOOL_SORT` Step names and values are changed to `SAMTOOLS_INDEX` and `SAMTOOLS_SORT`.

Please refer [PipelineStep](https://github.com/SanojPunchihewa/f5n/blob/master/app/src/main/java/com/mobilegenomics/f5n/core/PipelineStep.java)

**F5N Commits**

[PipelineStep](https://github.com/SanojPunchihewa/f5n/commit/1328598994ba0ea04268b98829ae977bec39ec99)
[GUIConfiguration](https://github.com/SanojPunchihewa/f5n/commit/1d87a596afc36a4fa9b2a60b5f7ca2e782a5cf7f)

**Comment by AnjanaSenanayake** [comment]
fixed a few days ago
